language: php

php:
  - '7.2'

#env:
#  - DB_HOST=127.0.0.1
#  - DB_DATABASE=default
#  - DB_USERNAME=root
#  - DB_PASSWORD=

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache

mysql:
  database: default
  username: root
  encoding: utf8


install:
  - composer update

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS default;'

script: vendor/bin/phpunit
