language: php

php:
  - '7.2'

env:
  - UNITENV=dist

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer update

before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `crcms_permission`;'

script: vendor/bin/phpunit --configuration phpunit.xml.$UNITENV
