<?php

namespace CrCms\Permission;

use CrCms\Foundation\ModuleServiceProvider;

/**
 * Class PermissionServiceProvider
 * @package CrCms\Permission
 */
class PermissionServiceProvider extends ModuleServiceProvider
{
    /**
     * @var string
     */
    protected $basePath = __DIR__ . DIRECTORY_SEPARATOR . '..' . DIRECTORY_SEPARATOR;

    /**
     * @var string
     */
    protected $name = 'permission';

    /**
     * @return void
     */
    public function boot(): void
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }

    /**
     * @return void
     */
    public function register(): void
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

    /**
     * 权限事件监听
     *
     * @return void
     */
    protected function repositoryListeners(): void
    {
    }
}
